name: morphaeus-paper
channels:
  - conda-forge
dependencies:
  - python=3
  - jupyterlab
  - yaml
  - natsort
  - ipython
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - scikit-image
  - opencv
  - pillow
  - seaborn
  - matplotlib
  - zarr
  - dask
  - napari
  - pyqt
  - tifffile
  - keras
  - tensorflow=2.15.0