name: morphaeus
channels:
  - conda-forge
  - labsyspharm
  - nodefaults
dependencies:
  - python=3.11
  - setuptools=68.2.2 # avoiding setuptools–Python3.11 incompatibilities
  - jupyterlab
  - yaml
  - natsort
  - ipython
  - ipywidgets
  - scipy
  - pillow
  - matplotlib 
  - napari['all']
  - pyqt
  - boto3
  - tqdm
  - imagecodecs
  - vae=0.0.7
