name: morphaeus-paper
channels:
  - conda-forge
dependencies:
  - python=3
  - jupyterlab
  - yaml
  - natsort
  - ipython
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - scikit-image
  - opencv
  - pillow
  - seaborn
  - matplotlib
  - 'zarr<3.0'  # zarr.open() fails in utils.single_channel_pyramid with zarr v3.0 
  - dask
  - napari['all']
  - pyqt
  - tifffile
  - keras
  - tensorflow=2.15.0