name: morphaeus
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - jupyterlab
  - yaml
  - natsort
  - ipython
  - ipywidgets
  - "blas=*=openblas" # force scipy to use OpenBlAS to avoid PC conflict with Tensorflow
  - scipy
  - pillow
  - matplotlib 
  - napari['all']
  - pyqt
  - boto3
  - tqdm
  - imagecodecs
