output_path: "./VAE9_VIG7"
# path to arbitrary output folder (created on-the-fly) 

csv_path: "../input/CyCIF-1A_clean_cylinter_clustering_3d_leiden.parquet"
# path to post-CyLinter spatial feature table

cluster_column: "cluster_3d"
# column name in CSV file that contains class or cluster labels from CyLinter

tif_path: "../input/CyCIF-1A_image.ome.tif"
# path to multi-channel image file

tif_channels: ["anti_CD3", "anti_CD45RO", "Keratin_570", "aSMA_660", "CD4_488", "CD45_PE", "PD1_647", "CD20_488", "CD68_555", "CD8a_660", "CD163_488", "FOXP3_570", "PDL1_647", "Ecad_488", "Vimentin_555", "CDX2_647", "LaminABC_488", "Desmin_555", "CD31_647", "PCNA_488", "CollagenIV_647"]
# channel names (as specified in markers.csv) in the order they appear in the multiplex image

contrast_path: "../input/CyCIF-1A_cylinter_contrast_limits.yml"
# image contrast settings previously defined in CyLinter

outlines_path: "../input/CyCIF-1A_seg_outlines.ome.tif"
# path to s3seg segmentation outlines

mask_path: "../input/CyCIF-1A_mask.tif"
# path to cell ID mask

markers_path: "../input/CyCIF-1A_mcmicro_markers.csv"
# path to MCMICRO markers metadata files

AAD: False  # the parameter is currently under development and not intended for demo use
# run automated artifact detection (AAD) on images

AAD_model_path: ""
# if AAD is TRUE, path to automated artifact detection model

percent_cells: 0.05
# fraction of cells in the spatial feature table (CSV at csv_path) to perform weighted random sample on according to cluster abundance

gallery_size: 240
# number of cells to be shown in the image patch gallery generated by module 3: generate_image_gallery.py gallery

window_size: 14
# squared dimension (in pixels) of image patches to be cropped from the multiplex image

cells_per_chunk: 1
# number of image patches in each chunk of the Zarr array used to store them

tiles_per_chunk: 5
# similar to cells_per_chunk, but passed to the "cut_tiles" command. Indicates the number of image tiles in each chunk of the Zarr array used to store them

cache_size_cellcutter: 57711  
# cellcutter cache size

latent_dimension: 412 # 10%
# VAE bottleneck size

cutoffs: [0.17, 99.99]
# lower and upper percentile cutoffs for clipping image channel intensities

batch_size: 64
# number of image patches to be fed at a time to VAE network during model training 

masked_model: True
# whether to apply vignette masking during model training

mask_std_dev: 7  # 18 actual (old method)
# size of Gaussian kernel used in vignette masking

learning_rate: 0.000001
# VAE model learning rate

training_epochs: 10
# number of times the full dataset has been seen by the network during model training

lasso_vector_tool: False
# toggle to use lasso vector tool to visualize clusters of image patch learned reconstructions

cluster_full_dataset: False
# whether to perform UMAP embedding and HDBSCAN clustering on combined training, validation, and test data (otherwise a sample of data whose size is specified by "clustering_sample_size" will be used)

clustering_sample_size: 1000
# sample size for clustering when "cluster_full_dataset" is False

embedding_algorithm: UMAP
# UMAP or TSNE

hdbscan_min_cluster_size: 50
# the smallest size grouping to be consider an HDBSCAN cluster

scatter_point_size: 50.0
# size of scatter points in encode_images.py module

zoom: 1.0
# fold-increase in the size of learned reconstructions shown in scatter plots 

channel_colors:
  CD4_488: 'tab:blue'
  Keratin_570: '#6eddff' 
  PCNA_488: 'tab:pink'
  CD68_555: 'tab:red'
  Ecad_488: '#ffff66'
  CD31_647: 'tab:orange'
  PDL1_647: '#66ff66'
  CD20_488: 'tab:purple'
  aSMA_660: 'tab:green'
  CD8a_660: 'tab:cyan'
  CD163_488: '#FF7F7F'
  Vimentin_555: 'tab:brown'
# look-up table for mapping channels to colors for visualization in encode_images.py module
